name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Generate Prisma Clients
        run: |
          npx prisma generate --schema=./libs/prisma-iam/src/prisma/schema.prisma
          npx prisma generate --schema=./libs/prisma-url/src/prisma/schema.prisma

      - uses: nrwl/nx-set-shas@v4

      - name: Run Tests and Build
        run: npx nx affected -t lint test build
